function a_plot(xyz)
    plot3(xyz(:,1), xyz(:,2), xyz(:,3), 'o', ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', 'white' ...
    );
%     patch(xyz(:,1), xyz(:,2), xyz(:,3), xyz(:,3), ...
%         'EdgeColor', 'interp', ...
%         'LineWidth', 5, ...
%         'FaceColor', 'none', ...
%         'FaceAlpha', 0.2, ...
%         'MarkerFaceColor', 'none', ...
%         'MarkerSize', 0.1 ...
%     );
    axis('equal');
end
